-- AlterTable
ALTER TABLE "User" ADD COLUMN     "apiTokensUsedThisMonth" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "apiUsageResetAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "plan" TEXT NOT NULL DEFAULT 'free',
ADD COLUMN     "planExpiresAt" TIMESTAMP(3),
ADD COLUMN     "storageUsedBytes" BIGINT NOT NULL DEFAULT 0;
